### ISSUE TITLE
Docman TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by wgosse** [f1nnix/docman#1]
c:\temp>docman c:\temp\Backup.postman_dump c:\temp\api_docs
Postman dump file path: c:\temp\Backup.postman_dump
Output directory: c:\temp\api_docs
C:\Users\wgosse\AppData\Roaming\npm\node_modules\docman\lib\generators\request.j
s:89
    if (request.responses.length === 0) {
                         ^
TypeError: Cannot read property 'length' of undefined
    at generateExampleResponses (C:\Users\wgosse\AppData\Roaming\npm\node_module
s\docman\lib\generators\request.js:89:26)
    at Object.module.exports [as request](C:UserswgosseAppDataRoamingnpmn
ode_modulesdocmanlibgeneratorsrequest.js:44:13)
    at C:\Users\wgosse\AppData\Roaming\npm\node_modules\docman\lib\generators\co
llections.js:38:28
    at Array.forEach (native)
    at C:\Users\wgosse\AppData\Roaming\npm\node_modules\docman\lib\generators\co
llections.js:37:27
    at Array.forEach (native)
    at Object.module.exports [as collections](C:UserswgosseAppDataRoamingn
pmnode_modulesdocmanlibgeneratorscollections.js:30:32)
    at module.exports (C:\Users\wgosse\AppData\Roaming\npm\node_modules\docman\l
ib\docman.js:16:23)
    at Object.<anonymous> (C:\Users\wgosse\AppData\Roaming\npm\node_modules\docm
an\bin\docman.js:38:1)
    at Module._compile (module.js:460:26)

c:\temp>

**Comment by f1nnix** [comment]
Gotcha, I'll fix ASAP! Maybe tomorrow. Some kind of test files will be appreciated (without your pricate API, certainly)

**Comment by wgosse** [comment]
Here’s the dump file I’m using.

**Comment by wgosse** [comment]
Also, I’m working with the latest and greatest postman.

The newer version allows for subfolder in a collection.  I don't know if docman is picking up on that and segmenting the output by subfolders in a collection as well as by collections.  It be great if it could. Thanks. 

From: Bill Gosse
Sent: Thursday, June 4, 2015 8:34 AM
To: 'f1nnix/docman'
Subject: RE: [docman] Docman TypeError: Cannot read property 'length' of undefined (#1)

Here’s the dump file I’m using.

**Comment by f1nnix** [comment]
@wgosse file is not attached, try again please. Also I'll add support for subfolders in a few days.

**Comment by wgosse** [comment]
I’ve attached a postman dump file to this email but I think the github comments maybe stripping it off.

If you don’t see it this time maybe you can sent an alternative email address that I could mail it to.

**Comment by wgosse** [comment]
My dump file below:

_(cut)_

**Comment by wgosse** [comment]
I was wondering if there was any movement on this issue at all?

**Comment by f1nnix** [comment]
Ah, sorry, this has been delayed a bit. I've got a strong deadline at my primary job. I do hope to fix the bug tomorrow +- 1 days.

**Comment by wgosse** [comment]
Thanks!

**Comment by f1nnix** [comment]
Still working on this.

I've fixed a bug with `if (request.responses.length === 0)`, but there's also one more little fix needed with body parameters.

![screen shot 2015-06-15 at 18 03 57](https://cloud.githubusercontent.com/assets/3099788/8163000/364813a4-1389-11e5-998f-4596b3c9bb99.png)

**Comment by f1nnix** [comment]
Ah, gotcha. You are using plain JSON-string, not form-data/urlencoded. Not sure if it's a proper way, but I'll add support for determining data-string as JSON-object.

![screen shot 2015-06-15 at 18 25 48](https://cloud.githubusercontent.com/assets/3099788/8163488/fec438d8-138b-11e5-825c-4eb76ca730de.png)

**Comment by f1nnix** [comment]
OK, I've build a PoC, should work OK. Which way to present body-data do you prefer? 

## 1

One way is to parse string data and present it as a Mardown table

![screen shot 2015-06-15 at 19 09 45](https://cloud.githubusercontent.com/assets/3099788/8164504/299d9936-1392-11e5-998c-dbeebe3abbd1.png)

## 2

The second way is just to print raw json as code block without any modifications.

Which one is the best for you? Tell me and I'll push the update to NPM

Thanks!

**Comment by wgosse** [comment]
I’m guessing Markdown would be good. Thanks

**Comment by f1nnix** [comment]
Just to be sure, we're talking about the same — first or second way? I mean, as for me, the **first** is better in your case because you're not using form-www/urlencoded, but sending plain JSON string (if it's not an error)

So, in your case it's better to output string payload as String, and not try to parse and present it as a table of form-data params. It will allow your users to copy payload JSON object instead of building JSON object from table theirselves.

But, it's up to you. So, 1st or 2nd?

``````
#### Body parameters

(raw payload)

```json
{
    "apiKey": "xxxxxx",
    "requestId": "test_campaignwins_accounts_all",
    "startDate": "2015-04-01",
    "endDate": "2015-04-30",
    "id": 2940,
    "accountIds": null,
    "campaignIds": null,
    "adIds": null,
    "exchangeIds": null,
    "statusIds": null
}```
``````

```
#### Body parameters

| key         | value                          |
|-------------|--------------------------------|
| apiKey      | xxxxxx                         |
| requestId   | test_campaignwins_accounts_all |
| startDate   | 2015-04-01                     |
| endDate     | 2015-04-30                     |
| id          | 2940                           |
| accountIds  | null                           |
| campaignIds | null                           |
| adIds       | null                           |
| exchangeIds | null                           |
| statusIds   | null                           |
```

**Comment by wgosse** [comment]
Let’s go with what you suggest is best . Thanks!

**Comment by f1nnix** [comment]
Done. Please, update your package to 0.4,

Thanks for contributing. Feel free to open new issues.

**Comment by wgosse** [comment]
Thanks!

**Comment by wgosse** [comment]
I'm still getting errors with this when I run against a dump that's a single collection with sub folders:
C:\Users\wgosse>docman C:\Dev\MoasisApi_PostmanTests\Moasis_API.json.postman_col
lection c:\temp\api_docs
Postman dump file path: C:\Dev\MoasisApi_PostmanTests\Moasis_API.json.postman_co
llection
Output directory: c:\temp\api_docs
C:\Users\wgosse\AppData\Roaming\npm\node_modules\docman\lib\generators\index.js:
11
    Postman.collections.forEach(function(collection) {
                       ^
TypeError: Cannot read property 'forEach' of undefined
    at Object.module.exports [as index](C:UserswgosseAppDataRoamingnpmnod
e_modulesdocmanlibgeneratorsindex.js:11:24)
    at module.exports (C:\Users\wgosse\AppData\Roaming\npm\node_modules\docman\l
ib\docman.js:15:16)
    at Object.<anonymous> (C:\Users\wgosse\AppData\Roaming\npm\node_modules\docm
an\bin\docman.js:38:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

C:\Users\wgosse>
